development:
  bucket: knowledgethief-dev
  access_key_id: replace_me
  secret_access_key: replace_me
test:
  bucket: knowledgethief-test
  access_key_id: replace_me
  secret_access_key: replace_me
production:
  bucket: knowledgethief-pro
  access_key_id: replace_me
  secret_access_key: replace_me
